### PR TITLE
z-index issue fix

### LINKED ISSUE #102: 2023.5 update causes strange effect
I upgraded Homeassistant to the latest 2023.5 version and now see a strange overlay effect with this card in the companion app as well as in a mobile chrome browser.

It seems the card does not respect layers of the UI or so. It does not hide behind the top bar on scrolling and also the side menu does not lie on top of this card. I hope the screenshot clarifies it..

image

### PR DESCRIPTION
**Pull request by bram2202**
- Remove z-index

Don't see the point of the z-index here.
Removed did not notice any other issues

closes #102

### CODE REVIEW

**Comment by bram2202** [comment]
Missed some z-index, removed them.

Also updated the js file in dist because I don't have the build config

**Comment by darkstoneathome** [comment]
@r-renato Could you approve the PR?

**Comment by jlaska** [comment]
@r-renato Is anything needed to increase confidence in this PR?

**Comment by gfay63** [comment]
THe fork from @bram2202 solved it for me as well. Please approve. And thanks again for the Integration! :)

**Comment by fubz** [comment]
@r-renato Help!  Please push this fix?

**Pull request merged**
